Repository TheRealSense/aalto-app, pull requests merged in 2018-12, with the labels that each got.

#37 App installation instructions added
  README.md
Labels: enhancement

#41 39/tools ui
  ios/AaltoApp.xcodeproj/project.pbxproj
  ios/AaltoApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/AaltoApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/AaltoApp.xcodeproj/xcshareddata/xcschemes/AaltoApp-tvOS.xcscheme
  ios/AaltoApp.xcodeproj/xcshareddata/xcschemes/AaltoApp.xcscheme
  ios/AaltoApp/Info.plist
  package-lock.json
  package.json
  src/auth/SignUp.js
  src/components/ToolHeader.js
  src/nav/Nav.js
  src/nav/tools.js
  src/nav/webViewComponent.js
  src/toolList.js
Labels: needs fixing

#42 NFC Routing to Tool pages
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/aaltoapp/MainApplication.java
  android/settings.gradle
  ios/AaltoApp.xcodeproj/project.pbxproj
  package-lock.json
  package.json
  src/nav/Home.js
Labels: feature
